title: Portfolio CSMS
description: Project portfolio showcasing my development work and progress through the CSMS Program at FSU
baseurl: ""
url: "https://jcpcsms.github.io"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
sass: 
  sass_dir: assets/css

  

# Blog settings
show_excerpts: true
