title: Portfolio CSMS
description: Project portfolio showcasing my development work and progress through the CSMS Program at FSU
baseurl: ""
url: "https://jcpcsms.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Blog settings
show_excerpts: true

paginate: 5
